services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      JINA_API_KEY: ${JINA_API_KEY}
      BRAVE_API_KEY: ${BRAVE_API_KEY}
