version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      JINA_API_KEY: ${JINA_API_KEY}
      BRAVE_API_KEY: ${BRAVE_API_KEY}
